services:
  app:
    build: ./backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: portal_cartas
      DB_USER: root
      DB_PASS: root
      DB_PORT: 3306
      JWT_SECRET: troque-esta-chave-em-producao

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: portal_cartas
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./backend/database/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
      - db_data:/var/lib/mysql

volumes:
  db_data:
